### ISSUE TITLE
Java 22 Has been Depricated 

### ISSUE THREAD

**Issue by vvenaya** [sainagh/meatballcraft#11]
I tried update prism launcher to Java 23 for improved performance, but it seems that Meatball craft is not compatible with Java 23, nor is it compatible with Java 21.

Any ideas on how to get it running on a recent Java platform ?

**Comment by vvenaya** [comment]
Note that the Wiki is showing instructions on how to use Java 22 (Which is nolonger available)

**Comment by PocketSkeleton** [comment]
You can still find Java 22 from the link (https://www.azul.com/downloads/?version=java-22&package=jdk&show-old-builds=true#zulu)

**Comment by sainagh** [comment]
That is why the tutorial specifically says:

you may have to click 'include older versions', make sure you pick the right operating system
