### ISSUE TITLE
UpdateRequest:EMC Gadgets

### ISSUE THREAD

**Issue by yuu1111** [sainagh/meatballcraft#2]
Thanks for including my mods. I haven't updated my mods in a few years, so I hope you'll be able to upgrade the versions of the mods in this ModPack!

I'm using machine translation, so sorry if the text is wrong!

Update details

# Update
## Update prerequisite mod version
  - BuildingGadgets-2.8.1 -> BuildingGadgets-2.8.4
  - ProjectEX-1.2.0.39 -> ProjectEX-1.2.0.40
## Bug fixes
  - Fixed a crash on division by zero when trying to place an item for which EMC does not exist.

Link to new version:https://www.curseforge.com/minecraft/mc-mods/emcgadgets/files/5412326

**Comment by sainagh** [comment]
Updated!
